import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,leaveWithReplacement,markManualRows,generate} from '../lib/schedule.ts';
function fixture(){const m=seed('2026-09');m.people.forEach((p,i)=>{p.type=i<2?'D':'N';p.off=[0,6]});m.leave={};for(let d=1;d<=30;d++)m.rows[d]=Object.fromEntries(m.people.map((p,i)=>[p.id,['D0','D1','N0','N1','N2','N3','N4','O','O'][i]]));m.prev=Object.fromEntries(m.people.map(p=>[p.id,'O']));return m}
test('leave and replacement apply atomically with a persistent manual marker',()=>{const m=fixture(),copy=structuredClone(m);const next=leaveWithReplacement('2026-09',m,'2',9,'7');assert.deepEqual(m,copy);assert.equal(next.rows[9]['2'],'L');assert.equal(next.rows[9]['7'],'N0');assert.deepEqual(next.leave['2'],[9]);assert.equal(JSON.parse(JSON.stringify(next)).manualDays[9],true)});
test('optional post worker may cover a required post without duplicating assignments',()=>{const next=leaveWithReplacement('2026-09',fixture(),'2',9,'6');assert.equal(next.rows[9]['6'],'N0');assert.ok(!Object.values(next.rows[9]).includes('N4'))});
test('failed replacement preserves both workers and leave list',()=>{const m=fixture(),copy=structuredClone(m);assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,'0'));assert.deepEqual(m,copy);assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,''),/인원 부족/)});
test('regular rest, annual limit and duplicate leave are rejected',()=>{let m=fixture();m.people[7].off=[3,6];assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,'7'),/정기휴무/);m=fixture();m.people[2].annual=1;assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,'7',1),/연간/);m.leave['2']=[9];assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,'7'),/이미/)});
test('replacement must respect previous-night and next-day rest including boundaries',()=>{let m=fixture();m.rows[8]['7']='N5';assert.throws(()=>leaveWithReplacement('2026-09',m,'0',9,'7'),/전날/);m=fixture();m.rows[10]['7']='D0';m.rows[10]['0']='O';assert.throws(()=>leaveWithReplacement('2026-09',m,'2',9,'7'),/야간 다음 날/);m=fixture();m.next['7']='D';assert.throws(()=>leaveWithReplacement('2026-09',m,'2',30,'7'),/다음 달/);m=fixture();m.prev['7']='U';assert.throws(()=>leaveWithReplacement('2026-09',m,'0',1,'7'),/전날/)});
test('manual labels ignore settings/no-op changes, survive undo snapshots, reset on regeneration',()=>{const m=fixture();const settings=structuredClone(m);settings.people[0].name='다른이름';assert.deepEqual(markManualRows(m,settings).manualDays,{});const after=structuredClone(m);after.rows[9]['2']='O';const marked=markManualRows(m,after);assert.equal(marked.manualDays[9],true);assert.equal(m.manualDays,undefined);assert.deepEqual(generate('2026-09',marked,1).manualDays,{})});
