import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,generate,inspect,stats,daysIn} from '../lib/schedule.ts';
const known=(key)=>{const m=seed(key);m.prev=Object.fromEntries(m.people.map(p=>[p.id,'O']));return m};
test('March draft covers essential sites while respecting rest and two days off',()=>{const key='2026-03';const m=generate(key,known(key));assert.equal(inspect(key,m).filter(i=>i.level==='error').length,0);assert.equal(Object.keys(m.rows).length,31);for(const p of m.people){const s=stats(key,m,p.id);assert.equal(s.day+s.night+s.off+s.leave,31)}for(const row of Object.values(m.rows)){assert.equal(Object.keys(row).length,9);assert.ok(Object.values(row).filter(v=>v==='O'||v==='L').length>=2);}});
test('Conflicting reference leave stays intact and shortages are disclosed',()=>{const key='2026-02';const m=generate(key,known(key));assert.equal(m.rows[16]['6'],'L');assert.equal(m.rows[17]['6'],'L');const errors=inspect(key,m).filter(i=>i.level==='error');assert.ok(errors.some(i=>i.day===16&&i.text.includes('인원 부족')));assert.ok(errors.some(i=>i.day===17&&i.text.includes('인원 부족')));assert.ok(!errors.some(i=>i.text.includes('야간 다음 날')));});
test('Previous month night duty cannot become next-day day duty',()=>{const key='2026-02';const base=known(key);base.prev=Object.fromEntries(base.people.map(p=>[p.id,'N']));const m=generate(key,base);for(const p of m.people.filter(p=>p.type==='N'))assert.ok(!m.rows[1][p.id].startsWith('D'));m.rows[1]['0']='D0';assert.ok(inspect(key,m).some(i=>i.day===1&&i.text.includes('야간 다음 날')));});
test('Next month day duty reserves month-end rest and leap year is correct',()=>{const key='2028-02';const base=known(key);base.next['0']='D';const m=generate(key,base);assert.equal(daysIn(key),29);assert.ok(!m.rows[29]['0'].startsWith('N'));assert.ok(inspect(key,m).some(i=>i.day===29&&i.text.includes('인원 부족')));assert.ok(!inspect(key,m).some(i=>i.text.includes('주간 전 휴식')))});
test('Duplicate posts and daytime-only violations are detected',()=>{const key='2026-03';const m=generate(key,known(key));m.rows[2]['2']='N0';m.rows[2]['4']='N0';const errors=inspect(key,m);assert.ok(errors.some(i=>i.text.includes('중복 배치')));assert.ok(errors.some(i=>i.text.includes('주간 전담자 야간')))});

test('Added and removed staff participate in generation dynamically',()=>{const key='2026-03';const base=known(key);base.people.push({id:'9',name:'신규',type:'N',off:[0,6],annual:0});base.leave['9']=[];base.prev['9']='O';base.next['9']='U';let m=generate(key,base);assert.equal(Object.keys(m.rows[1]).length,10);assert.equal(inspect(key,m).filter(i=>i.level==='error').length,0);m.people=m.people.filter(p=>p.id!=='9');delete m.leave['9'];delete m.prev['9'];delete m.next['9'];for(const row of Object.values(m.rows))delete row['9'];assert.equal(Object.keys(m.rows[1]).length,9);assert.ok(inspect(key,m).filter(i=>i.level==='error').length>0)});
