import {seed} from '@/lib/schedule';
import {isEditor} from '@/lib/editor-auth';
import {database} from '@/db/store';
import {z} from 'zod';
const person=z.object({id:z.string().regex(/^[a-zA-Z0-9_-]{1,40}$/),name:z.string().trim().min(1).max(12),type:z.enum(['D','N']),off:z.array(z.number().int().min(0).max(6)).length(2).refine(a=>new Set(a).size===2),annual:z.number().int().min(0).max(366)});
const code=z.enum(['O','L','D0','D1','N0','N1','N2','N3','N4','N5']);
const state=z.object({people:z.array(person).min(2).max(30).refine(a=>new Set(a.map(p=>p.id)).size===a.length&&new Set(a.map(p=>p.name)).size===a.length&&a.filter(p=>p.type==='D').length===2),leave:z.record(z.array(z.number().int().min(1).max(31))),rows:z.record(z.record(code)),prev:z.record(z.string().regex(/^(U|O|L|D[01]?|N[0-5]?)$/)),next:z.record(z.string().regex(/^(U|O|L|D[01]?|N[0-5]?)$/)),manualDays:z.record(z.string().regex(/^(?:[1-9]|[12][0-9]|3[01])$/),z.boolean()).optional(),note:z.string().max(1000)});
const keySchema=z.string().regex(/^20\d{2}-(0[1-9]|1[0-2])$/);
export async function GET(req:Request){try{const key=keySchema.parse(new URL(req.url).searchParams.get('month'));const db=database();const row=await db.prepare('SELECT data,revision FROM schedules WHERE month = ?').bind(key).first<{data:string;revision:number}>();const year=await db.prepare('SELECT month,data FROM schedules WHERE month LIKE ? AND month != ?').bind(key.slice(0,4)+'-%',key).all<{month:string;data:string}>();const annual:Record<string,number>={};for(const r of year.results){const m=JSON.parse(r.data);for(const [id,v]of Object.entries(m.leave))annual[id]=(annual[id]||0)+(v as number[]).length;}let defaults=seed(key);if(!row){const prior=await db.prepare('SELECT data FROM schedules WHERE month < ? ORDER BY month DESC LIMIT 1').bind(key).first<{data:string}>();if(prior){defaults.people=JSON.parse(prior.data).people;defaults.note='이전 저장 월의 근무자 설정을 가져왔습니다. 이번 달 휴무·연가와 월 경계 근무를 확인해 주세요.';}const [y,mm]=key.split('-').map(Number);const adjacent=(delta:number)=>{const d=new Date(y,mm-1+delta,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')};const prev=await db.prepare('SELECT data FROM schedules WHERE month = ?').bind(adjacent(-1)).first<{data:string}>();const next=await db.prepare('SELECT data FROM schedules WHERE month = ?').bind(adjacent(1)).first<{data:string}>();if(prev){const p=JSON.parse(prev.data);defaults.prev={...defaults.prev,...p.rows[new Date(y,mm-1,0).getDate()]};}if(next){defaults.next={...defaults.next,...JSON.parse(next.data).rows[1]};}}return Response.json({data:row?JSON.parse(row.data):null,defaults,revision:row?.revision||0,annual},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('Schedule read failed',e);return Response.json({error:'근무표를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'},{status:500});}}
export async function PUT(req:Request){try{if(req.headers.get('sec-fetch-site')==='cross-site')return Response.json({error:'허용되지 않은 요청입니다.'},{status:403});if(!await isEditor(req))return Response.json({error:'수정하려면 먼저 로그인해 주세요.'},{status:401});const raw=await req.text();if(raw.length>100000)return Response.json({error:'저장 용량을 초과했습니다.'},{status:413});const input=z.object({month:keySchema,revision:z.number().int().min(0),data:state}).parse(JSON.parse(raw));const {month,revision}=input;const savedAt=new Date().toISOString();const data={...input.data,savedAt};const db=database();const result=revision===0?await db.prepare('INSERT INTO schedules (month,data,revision) VALUES (?,?,1) ON CONFLICT(month) DO NOTHING').bind(month,JSON.stringify(data)).run():await db.prepare('UPDATE schedules SET data = ?, revision = revision+1 WHERE month = ? AND revision = ?').bind(JSON.stringify(data),month,revision).run();if(!result.meta.changes)return Response.json({error:'다른 창에서 이 달의 근무표가 변경되었습니다. 현재 내용을 백업한 뒤 새로 불러와 주세요.'},{status:409});return Response.json({revision:revision+1,savedAt});}catch(e){console.error('Schedule save failed',e);return Response.json({error:e instanceof z.ZodError?'설정을 확인해 주세요. 근무자는 2~30명, 주간 전담자는 2명이며 정기휴무는 각 2일이어야 합니다.':'저장하지 못했습니다. 편집 내용은 유지됩니다. 다시 저장해 주세요.'},{status:e instanceof z.ZodError?400:500});}}
